// 漕河泾印象城减脂餐厅数据
const restaurants = {
  main: [
    // 5星餐厅
    { id: 1, name: '钱屋·炭火烧烤 Yakiniku', emoji: '🥩', rating: 5, price: 398, cuisine: '日式烧肉', 
      recommend: '和牛刺身~120kcal\n烤牛舌~140kcal\n烤蔬菜~50kcal\n海鲜烤物~100kcal\n牛小排~220kcal',
      avoid: '五花肉~350kcal\n烤肠~300kcal\n刷酱烤肉~250kcal\n石锅拌饭~600kcal',
      tips: '优先刺身和烤海鲜，牛舌等瘦肉部位，少刷酱，搭配烤蔬菜，避免五花肉和石锅饭' },
    { id: 2, name: '喜家德虾仁水饺', emoji: '🥟', rating: 5, price: 15.5, cuisine: '饺子',
      recommend: '虾仁水饺(8个)~320kcal\n素三鲜水饺~280kcal\n凉拌菜~60kcal',
      avoid: '煎饺~420kcal\n红油抄手~450kcal\n炸酱面~550kcal',
      tips: '水饺煮制比煎饺健康，虾仁水饺蛋白优质，搭配凉拌菜，避免煎炸类' },
    { id: 3, name: '八合里牛肉火锅', emoji: '🔥', rating: 5, price: 120, cuisine: '潮汕火锅',
      recommend: '鲜切牛肉~150kcal/份\n牛百叶~80kcal\n蔬菜拼盘~40kcal\n清汤锅底~20kcal',
      avoid: '麻辣锅底~150kcal\n炸豆皮~180kcal\n肥牛卷(高脂)~300kcal',
      tips: '选清汤或骨汤锅底，牛肉选瘦肉部位，蔬菜多下，蘸料用酱油+蒜泥即可' },
    { id: 4, name: '云锦壹号·淮扬宴', emoji: '🍲', rating: 5, price: 190, cuisine: '淮扬菜',
      recommend: '清炖狮子头(瘦)~280kcal\n大煮干丝~180kcal\n清蒸鱼~200kcal\n蔬菜~60kcal',
      avoid: '红烧肉~550kcal\n松鼠桂鱼~600kcal\n蟹黄豆腐~380kcal',
      tips: '选清炖狮子头(瘦版)、大煮干丝和清蒸鱼，避免红烧肉、松鼠桂鱼和炒饭' },
    
    // 4星餐厅
    { id: 5, name: '谷牛和牛烤肉', emoji: '🥩', rating: 4, price: 145, cuisine: '日式烤肉',
      recommend: '牛舌~140kcal\n牛小排(瘦)~200kcal\n烤蔬菜~50kcal\n海鲜~100kcal',
      avoid: '五花肉~350kcal\n牛肋条(肥)~300kcal\n刷酱肉~250kcal',
      tips: '选牛舌、牛小排等瘦肉，搭配烤蔬菜，少刷酱，避免肥肉部位和石锅饭' },
    { id: 6, name: '太二酸菜鱼', emoji: '🐟', rating: 4, price: 87, cuisine: '酸菜鱼',
      recommend: '酸菜鱼(少汤)~280kcal\n清蒸时蔬~60kcal\n凉拌黄瓜~40kcal',
      avoid: '酸菜鱼汤泡饭~450kcal\n油炸小酥肉~380kcal\n红糖糍粑~320kcal',
      tips: '酸菜鱼少喝汤，搭配清蒸时蔬和凉菜，避免油炸小吃和糍粑' },
    { id: 7, name: '一绪に寿喜烧放题', emoji: '🔥', rating: 4, price: 183, cuisine: '日式自助',
      recommend: '和牛刺身~120kcal\n海鲜(虾/扇贝)~80kcal\n蔬菜拼盘~30kcal\n寿喜烧牛肉(少蘸料)~180kcal',
      avoid: '炸天妇罗~350kcal\n炸鸡块~400kcal\n芝士焗饭~500kcal',
      tips: '优先刺身海鲜区，蔬菜多拿，少蘸生蛋液外的酱料，避免油炸区和甜品区' },
    { id: 8, name: '湊湊火锅·茶憩', emoji: '🍲', rating: 4, price: 140, cuisine: '火锅',
      recommend: '清汤锅底~20kcal\n海鲜拼盘~200kcal\n鲜切牛肉~180kcal\n蔬菜~50kcal',
      avoid: '麻辣锅底~150kcal\n芝士丸~250kcal\n炸豆皮~180kcal',
      tips: '选清汤或花胶鸡锅底，多下海鲜和蔬菜，奶茶选无糖或少糖小杯' },
    { id: 9, name: '潮味狮头鹅·卤水火锅', emoji: '🦆', rating: 4, price: 122, cuisine: '潮汕菜',
      recommend: '卤水鹅肉(去皮)~180kcal\n鹅肝(少量)~150kcal\n卤水豆腐~80kcal\n蔬菜~40kcal',
      avoid: '鹅皮~280kcal\n卤水饭~450kcal\n蘸料(沙茶)~100kcal',
      tips: '鹅肉去皮吃，鹅肝少量尝味即可，多下蔬菜，避免鹅皮和卤水饭' },
    { id: 10, name: 'BAKER&SPICE', emoji: '🥗', rating: 4, price: 79, cuisine: '西餐',
      recommend: '沙拉(油醋汁)~250kcal\n三明治(烤鸡)~380kcal\n藜麦碗~320kcal',
      avoid: '奶油意面~600kcal\n芝士三明治~520kcal\n奶油浓汤~380kcal',
      tips: '选油醋汁沙拉、烤鸡三明治或藜麦碗，避免奶油类和芝士蛋糕' },
    { id: 11, name: '龙味馆·湘粤', emoji: '🥢', rating: 4, price: 114, cuisine: '粤菜馆',
      recommend: '清蒸鱼~200kcal\n白灼菜心~60kcal\n白切鸡(去皮)~180kcal\n蒸蛋~120kcal',
      avoid: '剁椒鱼头(油多)~480kcal\n小炒黄牛肉(油)~380kcal\n红烧肉~550kcal',
      tips: '选粤式清蒸、白灼类，避免湘式重油重辣的干锅和小炒' },
    { id: 12, name: '米村拌饭', emoji: '🍚', rating: 4, price: 31, cuisine: '快餐简餐',
      recommend: '石锅拌饭(少酱)~480kcal\n蔬菜拌饭~380kcal\n煎蛋~90kcal\n金枪鱼拌饭~420kcal',
      avoid: '芝士拌饭~600kcal\n五花肉拌饭~650kcal\n炸猪排拌饭~700kcal',
      tips: '选蔬菜拌饭或石锅拌饭少酱，避免芝士和五花肉款' },
    { id: 13, name: '江边城外烤全鱼', emoji: '🐟', rating: 4, price: 89, cuisine: '烤鱼',
      recommend: '烤鱼(香辣少放油)~350kcal\n清蒸鱼~200kcal\n蔬菜~60kcal\n蒜香烤鱼~380kcal',
      avoid: '烤鱼(重油麻辣)~550kcal\n炸鱼皮~380kcal\n干锅配菜~350kcal',
      tips: '选香辣或蒜香烤鱼(少油)，多下蔬菜，避免重油麻辣和油炸配菜' },
    { id: 14, name: '囍越越南餐厅', emoji: '🍜', rating: 4, price: 69, cuisine: '越南菜',
      recommend: '越南粉(清汤)~350kcal\n春卷(鲜虾)~180kcal\n凉拌米粉~280kcal',
      avoid: '炸春卷~350kcal\n咖喱饭~600kcal\n炸鸡翅~380kcal',
      tips: '选清汤粉类和鲜虾春卷，避免油炸和椰浆咖喱类' },
    { id: 15, name: '新发现', emoji: '🥗', rating: 4, price: 70, cuisine: '浙菜',
      recommend: '清蒸鱼~200kcal\n凉拌菜~80kcal\n白灼菜心~60kcal\n蒸蛋~120kcal',
      avoid: '糖醋排骨~500kcal\n东坡肉~600kcal\n油焖大虾~450kcal',
      tips: '多选清蒸鱼、白灼菜心和凉拌菜，避免糖醋、红烧肉和油炸类' },
    { id: 16, name: '泷川の深夜食堂', emoji: '🍣', rating: 4, price: 100, cuisine: '日本料理',
      recommend: '刺身拼盘~180kcal\n烤秋刀鱼~200kcal\n茶碗蒸~120kcal\n味噌汤~60kcal',
      avoid: '炸猪排~550kcal\n炸天妇罗~400kcal\n炸鸡块~450kcal',
      tips: '选刺身、烤鱼和茶碗蒸，避免油炸类和芝士焗饭' },
    { id: 17, name: '萨莉亚意式餐厅', emoji: '🍝', rating: 4, price: 50, cuisine: '意大利菜',
      recommend: '烤鸡~280kcal\n沙拉(油醋汁)~180kcal\n番茄意面~420kcal',
      avoid: '奶油意面~600kcal\n芝士焗饭~550kcal\n炸鸡翅~400kcal',
      tips: '选沙拉(油醋汁)、烤鸡或番茄意面，避免奶油类、披萨和炸物' },
    { id: 18, name: '肥汁米兰香港米线', emoji: '🍜', rating: 4, price: 40, cuisine: '米线',
      recommend: '香港米线(清汤)~380kcal\n蔬菜米线~320kcal\n瘦肉米线~400kcal\n番茄米线~420kcal',
      avoid: '肥汁米线(浓汤)~550kcal\n肥肠米线~600kcal\n炸蛋~180kcal',
      tips: '选清汤米线加蔬菜和瘦肉，避免肥汁浓汤和炸蛋' },
    { id: 19, name: '立方铁@铁板烧', emoji: '🍗', rating: 4, price: 96, cuisine: '铁板烧',
      recommend: '铁板蔬菜~150kcal\n鸡胸肉~200kcal\n铁板海鲜~180kcal\n铁板牛肉~350kcal',
      avoid: '铁板五花肉~450kcal\n芝士焗饭~600kcal\n炸鸡~400kcal',
      tips: '选铁板蔬菜、鸡胸肉和海鲜，要求少油，避免五花肉和芝士焗饭' },
    { id: 20, name: '小杨生煎', emoji: '🥟', rating: 4, price: 26, cuisine: '生煎',
      recommend: '鲜肉生煎(4个)~320kcal\n蔬菜生煎~280kcal\n小馄饨~280kcal',
      avoid: '虾仁生煎(油多)~400kcal\n双拼生煎~450kcal\n炸猪排~380kcal',
      tips: '选鲜肉或蔬菜生煎，避免虾仁生煎(油多)和炸物配菜' },
    { id: 21, name: '小女当家', emoji: '🍚', rating: 4, price: 38, cuisine: '快餐简餐',
      recommend: '蒸蛋~120kcal\n清炒时蔬~80kcal\n白灼虾~150kcal\n蒸鱼~180kcal',
      avoid: '红烧肉~450kcal\n糖醋里脊~400kcal\n油炸鸡排~380kcal',
      tips: '多选蒸蛋、蒸鱼、白灼虾和清炒时蔬，避免红烧、糖醋和油炸类' },
    { id: 22, name: '小江溪·江西菜', emoji: '🍜', rating: 4, price: 69, cuisine: '江西菜',
      recommend: '江西炒米粉(少油)~450kcal\n清炒时蔬~100kcal\n蒸蛋~120kcal\n凉拌菜~80kcal',
      avoid: '辣子鸡(油炸)~500kcal\n红烧肉~550kcal\n油焖笋~320kcal',
      tips: '炒米粉要求少油，搭配清炒时蔬和蒸蛋，避免油炸辣子鸡和干锅' },
    { id: 23, name: '町田商店·浓厚家系拉面', emoji: '🍜', rating: 4, price: 42, cuisine: '日式拉面',
      recommend: '清汤拉面~450kcal\n叉烧(瘦)~150kcal\n溏心蛋~70kcal\n味噌拉面~500kcal',
      avoid: '浓厚豚骨汤拉面~650kcal\n炸鸡块~380kcal\n煎饺~320kcal',
      tips: '选清汤或酱油汤底，少喝汤，叉烧选瘦肉，避免浓厚豚骨和配菜炸物' },
    { id: 24, name: '主老大·湖南下饭菜', emoji: '🥢', rating: 4, price: 69, cuisine: '湘菜',
      recommend: '辣椒炒肉(少油瘦肉)~320kcal\n蒸蛋~120kcal\n清炒时蔬~100kcal',
      avoid: '剁椒鱼头(油多)~480kcal\n小炒黄牛肉(油)~380kcal\n红烧肉~550kcal',
      tips: '辣椒炒肉要求少油瘦肉，搭配蒸蛋和清炒时蔬，避免剁椒鱼头和干锅' },
    { id: 25, name: '煲仔皇腊味煲仔饭', emoji: '🍳', rating: 4, price: 39, cuisine: '煲仔饭',
      recommend: '煲仔饭(去皮少油)~520kcal\n瘦肉煲仔饭~480kcal\n蔬菜~80kcal\n滑鸡煲仔饭~500kcal',
      avoid: '腊肠煲仔饭~650kcal\n五花肉煲仔饭~700kcal\n锅巴(多油)~300kcal',
      tips: '选瘦肉或滑鸡煲仔饭，少吃饭底锅巴，避免腊肠和五花肉' },
    { id: 26, name: '嘻小北·兰州清汤牛肉面', emoji: '🍜', rating: 4, price: 37, cuisine: '面馆',
      recommend: '牛肉面(清汤)~420kcal\n加牛肉~100kcal\n蔬菜~40kcal\n番茄牛肉面~450kcal',
      avoid: '红烧牛肉面~550kcal\n油炸面~500kcal\n辣椒油拌面~480kcal',
      tips: '选清汤牛肉面，少放辣油，避免红烧和油炸面' },
    { id: 27, name: '关东小磨东北菜', emoji: '🥢', rating: 4, price: 66, cuisine: '东北菜',
      recommend: '小鸡炖蘑菇(去皮)~380kcal\n炖菜~300kcal\n凉拌菜~80kcal\n酸菜白肉~400kcal',
      avoid: '锅包肉~550kcal\n地三鲜(油炸)~450kcal\n红烧肉~550kcal',
      tips: '选小鸡炖蘑菇(去皮)和炖菜，避免锅包肉和地三鲜等油炸' },
    { id: 28, name: '乌赤ATAPAS IZAKAYA', emoji: '🍛', rating: 4, price: 0, cuisine: '日式居酒屋',
      recommend: '刺身拼盘~180kcal\n烤物~200kcal\n沙拉~180kcal\n烤鳗鱼~350kcal',
      avoid: '炸鸡块~450kcal\n炸猪排~550kcal\n芝士焗饭~600kcal',
      tips: '选刺身、烤物和沙拉，避免油炸类和芝士焗饭' },
    { id: 29, name: '麦当劳', emoji: '🍔', rating: 4, price: 25, cuisine: '西式快餐',
      recommend: '麦辣鸡腿堡(去皮)~450kcal\n沙拉~150kcal\n烤鸡腿堡~420kcal\n双层吉士堡~480kcal',
      avoid: '巨无霸~550kcal\n麦辣鸡腿堡(带皮)~550kcal\n薯条(大)~380kcal',
      tips: '选烤鸡腿堡或沙拉，汉堡去皮吃，避免巨无霸、薯条和麦旋风' },
    { id: 30, name: '肯德基 KFC', emoji: '🍗', rating: 4, price: 30, cuisine: '西式快餐',
      recommend: '烤鸡腿堡~420kcal\n沙拉~150kcal\n烤鸡翅~280kcal\n新奥尔良烤鸡腿堡~450kcal',
      avoid: '炸鸡腿堡~550kcal\n炸鸡全家桶~1200kcal\n薯条(大)~400kcal',
      tips: '选烤鸡腿堡、沙拉或烤鸡翅，避免炸鸡全家桶和蛋挞' },
    { id: 31, name: '阿不就·台湾食堂', emoji: '🍱', rating: 4, price: 42, cuisine: '台湾菜',
      recommend: '卤肉饭(瘦肉版)~480kcal\n卤蛋~70kcal\n卤豆腐~80kcal\n烫青菜~60kcal',
      avoid: '卤肉饭(肥肉版)~600kcal\n炸鸡排~450kcal\n炸猪排~500kcal',
      tips: '卤肉饭选瘦肉版或少吃，搭配烫青菜，避免炸物和奶茶' },
    { id: 32, name: '大米先生·湘菜小炒', emoji: '🍚', rating: 4, price: 30, cuisine: '湘菜',
      recommend: '自选蔬菜~80kcal\n蒸蛋~120kcal\n白切鸡~180kcal\n小炒肉~350kcal',
      avoid: '红烧肉~450kcal\n油焖茄子~320kcal\n小炒黄牛肉(油)~350kcal',
      tips: '多选蔬菜、蒸蛋和白切鸡，避免重油重辣的小炒和红烧' },
    { id: 33, name: '俏阿妮·云南生烫牛肉米线', emoji: '🍜', rating: 4, price: 31, cuisine: '米线',
      recommend: '生烫牛肉米线~380kcal\n蔬菜米线~320kcal\n清汤米线~350kcal\n酸菜米线~400kcal',
      avoid: '肥肠米线~550kcal\n炸酱米线~500kcal\n油辣子米线~480kcal',
      tips: '选生烫牛肉米线或清汤米线，避免肥肠和油辣子' },
    { id: 34, name: '胡子大厨·超级小炒肉', emoji: '🌶️', rating: 4, price: 48, cuisine: '湘菜',
      recommend: '小炒肉(瘦肉版少油)~320kcal\n青椒肉丝~280kcal\n蔬菜~80kcal\n擂辣椒皮蛋~200kcal',
      avoid: '小炒肉(肥肉油多)~450kcal\n辣子鸡(油炸)~500kcal\n红烧肉~550kcal',
      tips: '小炒肉要求瘦肉版少油，搭配青椒肉丝和蔬菜，避免肥肉版和油炸' },
    { id: 35, name: '遇见小面', emoji: '🍜', rating: 4, price: 28, cuisine: '面馆',
      recommend: '清汤面~320kcal\n蔬菜面~280kcal\n牛肉面(清汤)~400kcal\n番茄面~380kcal',
      avoid: '红油面~480kcal\n炸酱面~500kcal\n肥肠面~550kcal',
      tips: '选清汤面或蔬菜面，避免红油和肥肠面' },
    { id: 36, name: 'Taco Bell塔可钟', emoji: '🌮', rating: 4, price: 31, cuisine: '西式快餐',
      recommend: '鸡肉塔可~220kcal\n沙拉~250kcal\n墨西哥卷(烤鸡)~320kcal\n牛肉塔可~280kcal',
      avoid: '炸鸡塔可~380kcal\n芝士Nachos~500kcal\n炸薯条~350kcal',
      tips: '选烤鸡肉塔可或墨西哥卷，避免炸鸡塔可和芝士Nachos' },
    { id: 37, name: '盖帮主·长沙现炒盖码饭', emoji: '🍚', rating: 4, price: 32, cuisine: '盖饭',
      recommend: '盖码饭(少汁瘦肉)~480kcal\n青椒肉丝盖饭~450kcal\n蔬菜盖饭~380kcal\n番茄炒蛋盖饭~420kcal',
      avoid: '红烧肉盖饭~650kcal\n辣子鸡盖饭~600kcal\n肥肠盖饭~600kcal',
      tips: '选青椒肉丝或蔬菜盖饭，要求少汁，避免红烧肉和肥肠' },
    { id: 38, name: '潮林卤大碗鹅肉饭', emoji: '🍚', rating: 4, price: 35, cuisine: '快餐简餐',
      recommend: '鹅肉饭(去皮)~450kcal\n卤蛋~70kcal\n卤豆腐~80kcal\n烫青菜~60kcal',
      avoid: '鹅皮饭~600kcal\n肥鹅肉饭~550kcal\n卤肉饭~580kcal',
      tips: '鹅肉去皮吃，搭配烫青菜，避免鹅皮和多汁饭' },
    { id: 39, name: '米陀饭团', emoji: '🍙', rating: 4, price: 17, cuisine: '小吃快餐',
      recommend: '饭团(非油炸)~280kcal\n瘦肉饭团~250kcal\n蔬菜饭团~220kcal\n金枪鱼饭团~300kcal',
      avoid: '油炸饭团~400kcal\n肥肉饭团~350kcal\n芝士饭团~380kcal',
      tips: '选非油炸的瘦肉或蔬菜饭团，避免油炸和芝士款' },
    
    // 3星餐厅
    { id: 40, name: '蚝大胆容边排骨·顺德干蒸', emoji: '🥩', rating: 3, price: 80, cuisine: '顺德菜',
      recommend: '顺德干蒸排骨(瘦)~280kcal\n蒸鱼~200kcal\n白灼虾~150kcal\n蔬菜~60kcal',
      avoid: '炸排骨~450kcal\n红烧肉~550kcal\n腊味~350kcal',
      tips: '选顺德干蒸排骨(少油)，搭配白灼虾和蔬菜' },
    { id: 41, name: '家府潮汕菜', emoji: '🥢', rating: 3, price: 85, cuisine: '潮汕菜',
      recommend: '潮汕牛肉火锅(清汤)~350kcal\n牛肉丸(瘦)~120kcal\n蔬菜拼盘~40kcal\n粿条(清汤)~300kcal',
      avoid: '卤味拼盘~450kcal\n炸粿肉~380kcal\n沙茶炒牛肉~450kcal',
      tips: '选清汤牛肉火锅，牛肉丸配蔬菜，避免卤味和油炸' },
    { id: 42, name: '福鼓·河豚蟹料理', emoji: '🍣', rating: 3, price: 280, cuisine: '日本料理',
      recommend: '河豚刺身~180kcal\n蟹肉刺身~120kcal\n烤蟹腿~150kcal\n蔬菜沙拉~80kcal',
      avoid: '炸河豚~400kcal\n天妇罗~350kcal\n蟹膏炒饭~550kcal',
      tips: '首选刺身和烤蟹腿，蔬菜沙拉搭配' },
    { id: 43, name: '眉州东坡·川菜', emoji: '🌶️', rating: 3, price: 95, cuisine: '川菜',
      recommend: '蒜泥白肉(瘦)~280kcal\n白灼菜心~60kcal\n清蒸鱼~200kcal\n宫保鸡丁(去皮)~320kcal',
      avoid: '水煮鱼~550kcal\n回锅肉~500kcal\n毛血旺~450kcal',
      tips: '选蒜泥白肉和清蒸鱼，避免水煮鱼和回锅肉' },
    { id: 44, name: '纯味斑鱼府', emoji: '🐟', rating: 3, price: 110, cuisine: '鱼火锅',
      recommend: '斑鱼火锅(清汤)~280kcal\n鱼片(瘦)~150kcal\n蔬菜拼盘~40kcal\n豆腐~80kcal',
      avoid: '麻辣锅底~200kcal\n炸鱼皮~320kcal\n蘸料(沙茶)~100kcal',
      tips: '选清汤锅底，鱼片涮着吃，蔬菜多下' },
    { id: 45, name: '石膳家·石锅拌饭', emoji: '🍚', rating: 3, price: 45, cuisine: '韩式料理',
      recommend: '石锅拌饭(少酱)~380kcal\n蔬菜拌饭~320kcal\n牛肉拌饭(瘦)~420kcal\n蒸蛋~120kcal',
      avoid: '芝士拌饭~550kcal\n五花肉拌饭~650kcal\n炸鸡拌饭~600kcal',
      tips: '选蔬菜拌饭或牛肉拌饭少酱，避免芝士和五花肉' },
    { id: 46, name: '老碗会·陕西手工面', emoji: '🍜', rating: 3, price: 35, cuisine: '西北菜',
      recommend: 'biangbiang面(少油)~480kcal\n羊肉汤面(清汤)~420kcal\n凉皮(少辣)~350kcal',
      avoid: '油泼面~550kcal\n炸酱面~500kcal\n肉夹馍~450kcal',
      tips: '选清汤羊肉面或凉皮少油，避免油泼面和肉夹馍' },
    { id: 47, name: '塔哈尔·新疆盛宴', emoji: '🥙', rating: 3, price: 88, cuisine: '新疆菜',
      recommend: '羊肉串(瘦)~150kcal\n烤馕(小份)~200kcal\n大盘鸡(去皮)~400kcal',
      avoid: '烤包子~380kcal\n丁丁炒面~500kcal\n油塔子~350kcal',
      tips: '选羊肉串和烤馕小份，大盘鸡去皮吃' },
    { id: 48, name: '锅气·湖南饭店', emoji: '🌶️', rating: 3, price: 65, cuisine: '湘菜',
      recommend: '辣椒炒肉(瘦肉少油)~300kcal\n蒸蛋~120kcal\n清炒时蔬~80kcal\n小炒鸡胗~200kcal',
      avoid: '剁椒鱼头~480kcal\n干锅肥肠~450kcal\n小炒黄牛肉(油)~380kcal',
      tips: '辣椒炒肉选瘦肉少油，搭配蒸蛋和蔬菜' },
    { id: 49, name: '京悦荟·京沪融合菜', emoji: '🥢', rating: 3, price: 120, cuisine: '融合菜',
      recommend: '北京烤鸭(去皮)~350kcal\n清蒸鱼~200kcal\n宫保鸡丁~320kcal\n蔬菜~60kcal',
      avoid: '烤鸭(带皮)~500kcal\n炸灌肠~350kcal\n京酱肉丝~450kcal',
      tips: '北京烤鸭去皮吃，选清蒸和宫保鸡丁' },
    { id: 50, name: '嘉美尚品·粤菜海鲜·港式茶点', emoji: '🦐', rating: 3, price: 150, cuisine: '粤菜',
      recommend: '虾饺皇(3个)~180kcal\n清蒸鲈鱼~200kcal\n白灼虾~150kcal\n蔬菜~60kcal',
      avoid: '叉烧包~350kcal\n蛋挞~280kcal\n炸春卷~350kcal',
      tips: '选虾饺皇、清蒸鱼和白灼虾，茶点选蒸制' },
    { id: 51, name: '达美乐比萨', emoji: '🍕', rating: 3, price: 55, cuisine: '比萨',
      recommend: '意式风情披萨(薄底小份)~400kcal\n烤鸡翅~250kcal\n蔬菜沙拉~150kcal',
      avoid: '美式披萨(厚底)~650kcal\n芝士披萨~700kcal\n薯条~350kcal',
      tips: '选薄底小份披萨，搭配烤鸡翅和蔬菜沙拉' },
    { id: 52, name: "Kathleen's Bistro&Bar 凯圣琳西餐厅", emoji: '🥩', rating: 3, price: 200, cuisine: '西餐',
      recommend: '烤鸡胸肉~200kcal\n牛排(瘦)~300kcal\n蔬菜沙拉(油醋)~150kcal\n烤三文鱼~280kcal',
      avoid: '奶油意面~650kcal\n炸薯条~350kcal\n汉堡~600kcal',
      tips: '选烤鸡胸、牛排或三文鱼，搭配蔬菜沙拉' },
    { id: 53, name: '海立阁海鲜江浙菜', emoji: '🦐', rating: 3, price: 180, cuisine: '江浙菜',
      recommend: '清蒸蟹~200kcal\n白灼虾~150kcal\n蔬菜~60kcal\n清蒸鱼~200kcal',
      avoid: '油爆虾~400kcal\n红烧肉~550kcal\n糖醋鱼~500kcal',
      tips: '选清蒸蟹和白灼虾，搭配蔬菜，避免油爆和糖醋' },
    { id: 54, name: '椒锅锅·麻辣香锅', emoji: '🌶️', rating: 3, price: 42, cuisine: '香锅',
      recommend: '麻辣香锅(素菜为主)~350kcal\n鸡胸肉~150kcal\n蔬菜拼盘~80kcal\n藕片~80kcal',
      avoid: '麻辣香锅(五花肉)~550kcal\n炸鸡腿~400kcal\n油炸豆皮~200kcal',
      tips: '选素菜为主加鸡胸肉，要求少油，避免五花肉' },
    { id: 55, name: 'Potato Corner', emoji: '🍟', rating: 3, price: 25, cuisine: '西式快餐',
      recommend: '迷你薯条(小份)~180kcal\n蔬菜条~50kcal\n鸡块(小份)~150kcal',
      avoid: '大份薯条~400kcal\n芝士薯条~450kcal\n炸洋葱圈~350kcal',
      tips: '选迷你薯条小份，搭配蔬菜条，避免大份' },
    { id: 56, name: '1973继光香香鸡', emoji: '🍗', rating: 3, price: 28, cuisine: '炸鸡炸串',
      recommend: '香香鸡(去皮)~250kcal\n蔬菜~60kcal\n鸡米花(小份)~200kcal',
      avoid: '香香鸡(带皮)~380kcal\n炸鸡腿~400kcal\n炸鸡排~450kcal',
      tips: '香香鸡去皮吃，搭配蔬菜，避免带皮炸鸡' },
    { id: 57, name: '麻源口·江西米粉', emoji: '🍜', rating: 3, price: 26, cuisine: '快餐简餐',
      recommend: '牛肉米粉(清汤)~380kcal\n蔬菜米粉~300kcal\n鸡蛋米粉~350kcal\n酸菜米粉~320kcal',
      avoid: '肥肠米粉~550kcal\n炸酱米粉~480kcal\n油辣子米粉~450kcal',
      tips: '选清汤牛肉或蔬菜米粉，避免肥肠和油辣子' },
    { id: 58, name: '满巍明生炸鸡架', emoji: '🍗', rating: 3, price: 22, cuisine: '炸鸡炸串',
      recommend: '生炸鸡架(小份)~200kcal\n炸鸡柳(小份)~180kcal\n蔬菜~60kcal',
      avoid: '鸡架全家福~450kcal\n炸鸡腿~400kcal\n炸鸡排~450kcal',
      tips: '选小份生炸鸡架或鸡柳，搭配蔬菜' },
    { id: 59, name: '馋三尺蟹粉小笼', emoji: '🥟', rating: 3, price: 45, cuisine: '小笼',
      recommend: '蟹粉小笼(4个)~320kcal\n鲜肉小笼(4个)~280kcal\n蔬菜~60kcal\n小馄饨~250kcal',
      avoid: '蟹粉小笼(油炸)~420kcal\n炸春卷~350kcal\n蟹粉灌汤包~450kcal',
      tips: '选蒸制小笼包，蟹粉小笼限量，搭配蔬菜' },
    { id: 60, name: '可可牛·现卤鲜牛肉饭', emoji: '🍚', rating: 3, price: 38, cuisine: '快餐简餐',
      recommend: '卤牛肉饭(瘦肉)~450kcal\n卤蛋~70kcal\n卤豆腐~80kcal\n烫青菜~60kcal',
      avoid: '卤肉饭(肥肉)~600kcal\n炸猪排~450kcal\n炸鸡腿~400kcal',
      tips: '选卤牛肉饭(瘦肉)，搭配卤蛋和烫青菜' },
  ],
  
  drinks: [
    // 5星
    { id: 101, name: '柠季·手打柠檬茶', emoji: '🍵', rating: 5, price: 15, cuisine: '茶饮果汁',
      recommend: '手打柠檬茶(无糖)~60kcal\n茉莉柠檬(少糖)~80kcal\n鸭屎香柠檬茶(少糖)~100kcal',
      avoid: '柠檬茶(全糖)~180kcal\n芝士柠檬茶~250kcal\n椰椰柠檬~200kcal',
      tips: '选手打柠檬茶无糖或茉莉柠檬少糖，避免全糖和芝士款' },
    { id: 102, name: '煲珠公·老红糖珍珠奶茶', emoji: '🧋', rating: 5, price: 14, cuisine: '茶饮果汁',
      recommend: '珍珠奶茶(无糖少冰)~180kcal\n老红糖奶茶(少糖)~160kcal\n纯茶~30kcal',
      avoid: '珍珠奶茶(全糖)~280kcal\n焦糖奶茶~250kcal\n布丁奶茶~300kcal',
      tips: '选无糖少冰珍珠奶茶或老红糖少糖，避免全糖和布丁款' },
    
    // 4星
    { id: 103, name: '淡马茶坊', emoji: '🧋', rating: 4, price: 22, cuisine: '茶饮果汁',
      recommend: '黄皮水(少糖)~100kcal\n柠檬茶(无糖)~60kcal\n茉莉茶~50kcal\n水果茶(少糖)~120kcal',
      avoid: '珍珠奶茶~350kcal\n芝士奶盖~300kcal\n椰椰芒芒~280kcal',
      tips: '选黄皮水少糖或柠檬茶无糖，避免珍珠奶茶和芝士奶盖' },
    { id: 104, name: '瑞幸咖啡', emoji: '☕', rating: 4, price: 13, cuisine: '咖啡',
      recommend: '美式~10kcal\n拿铁(无糖)~120kcal\n生椰拿铁(无糖)~165kcal\n橙C美式~80kcal',
      avoid: '陨石拿铁~300kcal\n焦糖玛奇朵~280kcal\n厚乳拿铁~270kcal',
      tips: '减脂期首选美式或无糖拿铁，生椰拿铁一周1-2次即可' },
    { id: 105, name: 'BeanStar比星咖啡', emoji: '☕', rating: 4, price: 19, cuisine: '咖啡',
      recommend: '美式~15kcal\n澳白(无糖)~100kcal\n拿铁(无糖)~120kcal\n气泡美式~50kcal',
      avoid: '焦糖拿铁~260kcal\n摩卡~320kcal\n榛果拿铁~250kcal',
      tips: '首选美式或无糖澳白，避免焦糖和榛果风味款' },
    { id: 106, name: 'LAVAZZA拉瓦萨咖啡', emoji: '☕', rating: 4, price: 28, cuisine: '咖啡',
      recommend: '美式~15kcal\n拿铁(无糖)~120kcal\n冷萃~15kcal\n燕麦拿铁~130kcal',
      avoid: '焦糖玛奇朵~280kcal\n摩卡~320kcal\n榛果拿铁~250kcal',
      tips: '首选美式或无糖拿铁，避免焦糖玛奇朵和摩卡' },
    
    // 3星
    { id: 107, name: '喜茶', emoji: '🧋', rating: 3, price: 20, cuisine: '茶饮果汁',
      recommend: '椰椰芒芒(少冰少糖)~150kcal\n多肉葡萄(少糖)~140kcal\n满杯水果茶~120kcal\n纯绿研(无糖)~30kcal',
      avoid: '芋泥波波~300kcal\n芝士蛋糕奶茶~350kcal\n芝士葡萄~280kcal',
      tips: '选椰椰芒芒少糖或满杯水果茶，避免芋泥和芝士系列' },
    { id: 108, name: '奈雪的茶', emoji: '🧋', rating: 3, price: 23, cuisine: '茶饮果汁',
      recommend: '霸气葡萄(少糖)~140kcal\n纯茶~30kcal\n水果茶(少糖)~120kcal\n茉莉毛尖~50kcal',
      avoid: '芋泥宝藏茶~320kcal\n芝士蛋糕奶茶~350kcal\n霸气芝士草莓~280kcal',
      tips: '选霸气葡萄少糖或纯茶，避免芋泥宝藏茶和芝士蛋糕款' },
    { id: 109, name: 'LELECHA乐乐茶', emoji: '🧋', rating: 3, price: 22, cuisine: '茶饮果汁',
      recommend: '椰椰芒果(少糖)~150kcal\n满杯水果茶~120kcal\n纯茶~30kcal\n茉莉奶绿(无糖)~80kcal',
      avoid: '芋泥波波~300kcal\n芝士蛋糕奶茶~350kcal\n脏脏系列~280kcal',
      tips: '选椰椰芒果少糖或纯茶，避免芋泥和芝士蛋糕款' },
    { id: 110, name: 'M Stand', emoji: '🥤', rating: 4, price: 40, cuisine: '茶饮果汁',
      recommend: '燕麦拿铁(无糖)~130kcal\n冷萃~15kcal\n美式~15kcal\n手冲~20kcal',
      avoid: '太妃拿铁~320kcal\n摩卡~350kcal\n焦糖玛奇朵~280kcal',
      tips: '首选美式或冷萃，拿铁选无糖燕麦奶，避免太妃和摩卡' },
    { id: 111, name: '星巴克', emoji: '☕', rating: 4, price: 38, cuisine: '咖啡',
      recommend: '美式咖啡(无糖)~15kcal\n冷萃~15kcal\n拿铁(无糖)~120kcal\n燕麦拿铁~130kcal',
      avoid: '星冰乐~450kcal\n焦糖玛奇朵~280kcal\n摩卡星冰乐~450kcal',
      tips: '首选美式或冷萃，拿铁选无糖，避免星冰乐和摩卡' },
    { id: 112, name: 'Blueglass酸奶', emoji: '🥛', rating: 4, price: 35, cuisine: '酸奶鲜奶',
      recommend: '原味酸奶~100kcal\n益生菌系列~90kcal\n裸酸奶~80kcal\n燕麦酸奶~150kcal',
      avoid: '果味酸奶~180kcal\n奥利奥酸奶~250kcal\n芝士奶盖款~300kcal',
      tips: '选原味或益生菌系列，避免奥利奥和芝士奶盖' },
    { id: 113, name: 'Manner Coffee', emoji: '☕', rating: 4, price: 20, cuisine: '咖啡',
      recommend: '美式~15kcal\n澳白(无糖)~100kcal\n拿铁(无糖)~120kcal\n气泡美式~50kcal',
      avoid: '焦糖拿铁~260kcal\n摩卡~320kcal\n风味特调~240kcal',
      tips: '首选美式或无糖澳白，避免焦糖和风味特调' },
    
    // 2星
    { id: 114, name: '霸王茶姬', emoji: '🥤', rating: 4, price: 20, cuisine: '茶饮果汁',
      recommend: '伯牙绝弦(三分糖)~150kcal\n茉莉奶绿(无糖)~80kcal\n桂花引(三分糖)~140kcal',
      avoid: '芝士奶盖系列~350kcal\n奶茶(全糖)~280kcal\n芋泥系列~300kcal',
      tips: '选茉莉奶绿无糖或伯牙绝弦三分糖，避免芝士奶盖和芋泥' },
    { id: 115, name: '茉莉奶白', emoji: '🥤', rating: 4, price: 19, cuisine: '茶饮果汁',
      recommend: '茉莉奶茶(少冰少糖)~160kcal\n白玉兰(三分糖)~140kcal\n茉莉清茶~50kcal\n白桃乌龙~120kcal',
      avoid: '芝士奶盖款~340kcal\n全糖奶茶~280kcal\n巧克力系列~320kcal',
      tips: '选茉莉清茶或少糖茉莉奶茶，避免芝士奶盖和全糖' },
    { id: 116, name: '茉酸奶', emoji: '🥛', rating: 4, price: 24, cuisine: '酸奶鲜奶',
      recommend: '原味酸奶~90kcal\n低卡系列~80kcal\n牛油果酸奶(无糖)~150kcal\n蓝莓酸奶~150kcal',
      avoid: '草莓芝士~220kcal\n巧克力酸奶~280kcal\n芒果酸奶~200kcal',
      tips: '选原味或低卡系列，牛油果酸奶无糖版可偶尔喝' },
    { id: 117, name: 'DQ蛋糕冰淇淋', emoji: '🍦', rating: 4, price: 28, cuisine: '冰淇淋',
      recommend: '甜筒(小份)~180kcal\n冰淇淋(小杯)~200kcal\n香蕉船~380kcal',
      avoid: '暴风雪系列~450kcal\n蛋糕冰淇淋~600kcal\n圣代~350kcal',
      tips: '选小份甜筒或小杯冰淇淋，避免暴风雪和蛋糕冰淇淋' },
    { id: 118, name: '椿风·养生茶饮', emoji: '🍵', rating: 4, price: 18, cuisine: '茶饮果汁',
      recommend: '草本茶~10kcal\n鲜果茶(无糖)~60kcal\n桂花乌龙~20kcal\n绿豆沙~180kcal',
      avoid: '珍珠奶茶~350kcal\n芝士奶盖茶~380kcal\n芋泥奶茶~320kcal',
      tips: '选草本茶或无糖鲜果茶，避免珍珠奶茶和芝士奶盖' },
    { id: 119, name: 'Yee3三号椰·椰子炒冰', emoji: '🥥', rating: 4, price: 19, cuisine: '冰淇淋',
      recommend: '椰子炒冰~180kcal\n原味椰子水~45kcal\n椰奶(无糖)~80kcal\n芒果椰子冰~200kcal',
      avoid: '加料款(珍珠/芋圆)~250kcal\n巧克力风味~280kcal\n加糖浆款~220kcal',
      tips: '选原味椰子水或椰子炒冰，避免加料和糖浆' },
    { id: 120, name: '匡朵·厚乳酪裸蛋糕', emoji: '🧊', rating: 4, price: 31, cuisine: '甜品',
      recommend: '切片蛋糕(小份)~280kcal\n裸蛋糕(少奶油)~250kcal\n提拉米苏~320kcal\n抹茶蛋糕~300kcal',
      avoid: '整块蛋糕~800kcal\n奶油蛋糕~450kcal\n芝士蛋糕~400kcal',
      tips: '选小份切片或裸蛋糕，控制份量，避免整块和重奶油' },
    { id: 121, name: '朴下隆九', emoji: '🍞', rating: 2, price: 25, cuisine: '面包蛋糕',
      recommend: '全麦面包(小份)~150kcal\n贝果~180kcal\n蔬菜沙拉~120kcal',
      avoid: '丹麦酥~350kcal\n奶油面包~300kcal\n可颂~380kcal\n蛋糕~400kcal',
      tips: '选全麦面包或贝果，搭配蔬菜沙拉，避免丹麦酥和奶油类' },
    { id: 122, name: '薛记炒货', emoji: '🌰', rating: 2, price: 30, cuisine: '栗子/干果',
      recommend: '栗子(小份)~150kcal\n核桃(小份)~180kcal\n瓜子~100kcal',
      avoid: '焦糖瓜子~200kcal\n奶香夏威夷果~300kcal\n油炸花生米~250kcal',
      tips: '选栗子或核桃小份，瓜子适量，避免焦糖和油炸类' },
    { id: 123, name: '琦王花生', emoji: '🌰', rating: 2, price: 20, cuisine: '栗子/干果',
      recommend: '栗子(小份)~150kcal\n核桃~180kcal\n腰果(小份)~160kcal',
      avoid: '糖炒栗子~200kcal\n盐焗腰果~220kcal\n油炸花生~250kcal',
      tips: '选栗子或核桃小份，原味坚果，避免糖炒和油炸' },
    { id: 124, name: 'UH祐禾', emoji: '🍞', rating: 2, price: 38, cuisine: '面包蛋糕',
      recommend: '全麦吐司(小份)~150kcal\n贝果~180kcal\n三明治(鸡胸)~250kcal',
      avoid: '肉松面包~350kcal\n奶油面包~300kcal\n丹麦酥~380kcal\n蛋糕~400kcal',
      tips: '选全麦吐司或贝果，三明治选鸡胸肉馅，避免肉松和奶油类' },
    { id: 125, name: "Pantry's Best派悦坊蛋糕", emoji: '🍰', rating: 2, price: 47, cuisine: '甜品',
      recommend: '迷你蛋糕(1小块)~200kcal\n水果蛋糕~250kcal\n轻芝士蛋糕~220kcal',
      avoid: '大份蛋糕~500kcal\n奶油蛋糕~450kcal\n巧克力蛋糕~400kcal\n拿破仑~450kcal',
      tips: '选迷你蛋糕或轻芝士蛋糕，控制份量，避免大份和巧克力款' },
    { id: 126, name: '野人先生Gelato', emoji: '🍦', rating: 2, price: 30, cuisine: '冰淇淋',
      recommend: '冰淇淋(小份)~150kcal\n水果口味~120kcal\n椰子口味~140kcal\n双球(小份)~200kcal',
      avoid: '大份冰淇淋~350kcal\n巧克力口味~200kcal\n饼干碎~180kcal\n华夫饼~200kcal',
      tips: '选小份或水果口味，避免大份和巧克力饼干碎款' },
  ]
};

// 导出
if (typeof module !== 'undefined' && module.exports) {
  module.exports = restaurants;
}
